// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/akolybelnikov/flashcards/db (interfaces: FlashcardRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_flashcard_repository.go -package=mocks github.com/akolybelnikov/flashcards/db FlashcardRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/akolybelnikov/flashcards/models"
	gomock "go.uber.org/mock/gomock"
)

// MockFlashcardRepository is a mock of FlashcardRepository interface.
type MockFlashcardRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFlashcardRepositoryMockRecorder
	isgomock struct{}
}

// MockFlashcardRepositoryMockRecorder is the mock recorder for MockFlashcardRepository.
type MockFlashcardRepositoryMockRecorder struct {
	mock *MockFlashcardRepository
}

// NewMockFlashcardRepository creates a new mock instance.
func NewMockFlashcardRepository(ctrl *gomock.Controller) *MockFlashcardRepository {
	mock := &MockFlashcardRepository{ctrl: ctrl}
	mock.recorder = &MockFlashcardRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlashcardRepository) EXPECT() *MockFlashcardRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFlashcardRepository) Create(req *models.CreateFlashcardRequest) (*models.Flashcard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", req)
	ret0, _ := ret[0].(*models.Flashcard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockFlashcardRepositoryMockRecorder) Create(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFlashcardRepository)(nil).Create), req)
}

// Delete mocks base method.
func (m *MockFlashcardRepository) Delete(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFlashcardRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFlashcardRepository)(nil).Delete), id)
}

// GetAll mocks base method.
func (m *MockFlashcardRepository) GetAll() ([]*models.Flashcard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]*models.Flashcard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockFlashcardRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockFlashcardRepository)(nil).GetAll))
}

// GetByID mocks base method.
func (m *MockFlashcardRepository) GetByID(id int) (*models.Flashcard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.Flashcard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockFlashcardRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockFlashcardRepository)(nil).GetByID), id)
}

// GetRandom mocks base method.
func (m *MockFlashcardRepository) GetRandom() (*models.Flashcard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandom")
	ret0, _ := ret[0].(*models.Flashcard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRandom indicates an expected call of GetRandom.
func (mr *MockFlashcardRepositoryMockRecorder) GetRandom() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandom", reflect.TypeOf((*MockFlashcardRepository)(nil).GetRandom))
}

// Update mocks base method.
func (m *MockFlashcardRepository) Update(id int, req *models.UpdateFlashcardRequest) (*models.Flashcard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, req)
	ret0, _ := ret[0].(*models.Flashcard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockFlashcardRepositoryMockRecorder) Update(id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFlashcardRepository)(nil).Update), id, req)
}
