// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/akolybelnikov/flashcards/services (interfaces: TranslationCache)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_translation_cache.go -package=mocks github.com/akolybelnikov/flashcards/services TranslationCache
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	services "github.com/akolybelnikov/flashcards/services"
	gomock "go.uber.org/mock/gomock"
)

// MockTranslationCache is a mock of TranslationCache interface.
type MockTranslationCache struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationCacheMockRecorder
	isgomock struct{}
}

// MockTranslationCacheMockRecorder is the mock recorder for MockTranslationCache.
type MockTranslationCacheMockRecorder struct {
	mock *MockTranslationCache
}

// NewMockTranslationCache creates a new mock instance.
func NewMockTranslationCache(ctrl *gomock.Controller) *MockTranslationCache {
	mock := &MockTranslationCache{ctrl: ctrl}
	mock.recorder = &MockTranslationCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationCache) EXPECT() *MockTranslationCacheMockRecorder {
	return m.recorder
}

// GenerateKey mocks base method.
func (m *MockTranslationCache) GenerateKey(content, fromLang, toLang string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateKey", content, fromLang, toLang)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateKey indicates an expected call of GenerateKey.
func (mr *MockTranslationCacheMockRecorder) GenerateKey(content, fromLang, toLang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateKey", reflect.TypeOf((*MockTranslationCache)(nil).GenerateKey), content, fromLang, toLang)
}

// Get mocks base method.
func (m *MockTranslationCache) Get(key string) (*services.CachedTranslation, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(*services.CachedTranslation)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTranslationCacheMockRecorder) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTranslationCache)(nil).Get), key)
}

// Set mocks base method.
func (m *MockTranslationCache) Set(key string, translation *services.CachedTranslation) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", key, translation)
}

// Set indicates an expected call of Set.
func (mr *MockTranslationCacheMockRecorder) Set(key, translation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockTranslationCache)(nil).Set), key, translation)
}

// StartCleanup mocks base method.
func (m *MockTranslationCache) StartCleanup(interval time.Duration, stopChan <-chan struct{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartCleanup", interval, stopChan)
}

// StartCleanup indicates an expected call of StartCleanup.
func (mr *MockTranslationCacheMockRecorder) StartCleanup(interval, stopChan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartCleanup", reflect.TypeOf((*MockTranslationCache)(nil).StartCleanup), interval, stopChan)
}
