// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/akolybelnikov/flashcards/services (interfaces: FlashcardServiceInterface)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_flashcard_service.go -package=mocks github.com/akolybelnikov/flashcards/services FlashcardServiceInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/akolybelnikov/flashcards/models"
	gomock "go.uber.org/mock/gomock"
)

// MockFlashcardServiceInterface is a mock of FlashcardServiceInterface interface.
type MockFlashcardServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockFlashcardServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockFlashcardServiceInterfaceMockRecorder is the mock recorder for MockFlashcardServiceInterface.
type MockFlashcardServiceInterfaceMockRecorder struct {
	mock *MockFlashcardServiceInterface
}

// NewMockFlashcardServiceInterface creates a new mock instance.
func NewMockFlashcardServiceInterface(ctrl *gomock.Controller) *MockFlashcardServiceInterface {
	mock := &MockFlashcardServiceInterface{ctrl: ctrl}
	mock.recorder = &MockFlashcardServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlashcardServiceInterface) EXPECT() *MockFlashcardServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateFlashcard mocks base method.
func (m *MockFlashcardServiceInterface) CreateFlashcard(req *models.CreateFlashcardRequest) (*models.Flashcard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFlashcard", req)
	ret0, _ := ret[0].(*models.Flashcard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFlashcard indicates an expected call of CreateFlashcard.
func (mr *MockFlashcardServiceInterfaceMockRecorder) CreateFlashcard(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFlashcard", reflect.TypeOf((*MockFlashcardServiceInterface)(nil).CreateFlashcard), req)
}

// DeleteFlashcard mocks base method.
func (m *MockFlashcardServiceInterface) DeleteFlashcard(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFlashcard", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFlashcard indicates an expected call of DeleteFlashcard.
func (mr *MockFlashcardServiceInterfaceMockRecorder) DeleteFlashcard(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFlashcard", reflect.TypeOf((*MockFlashcardServiceInterface)(nil).DeleteFlashcard), id)
}

// GenerateAIHint mocks base method.
func (m *MockFlashcardServiceInterface) GenerateAIHint(flashcard *models.Flashcard, lang string) *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAIHint", flashcard, lang)
	ret0, _ := ret[0].(*string)
	return ret0
}

// GenerateAIHint indicates an expected call of GenerateAIHint.
func (mr *MockFlashcardServiceInterfaceMockRecorder) GenerateAIHint(flashcard, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAIHint", reflect.TypeOf((*MockFlashcardServiceInterface)(nil).GenerateAIHint), flashcard, lang)
}

// GenerateTranslation mocks base method.
func (m *MockFlashcardServiceInterface) GenerateTranslation(req *models.GenerateTranslationRequest) (*models.GenerateTranslationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTranslation", req)
	ret0, _ := ret[0].(*models.GenerateTranslationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateTranslation indicates an expected call of GenerateTranslation.
func (mr *MockFlashcardServiceInterfaceMockRecorder) GenerateTranslation(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTranslation", reflect.TypeOf((*MockFlashcardServiceInterface)(nil).GenerateTranslation), req)
}

// GetAllFlashcards mocks base method.
func (m *MockFlashcardServiceInterface) GetAllFlashcards() ([]*models.Flashcard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllFlashcards")
	ret0, _ := ret[0].([]*models.Flashcard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllFlashcards indicates an expected call of GetAllFlashcards.
func (mr *MockFlashcardServiceInterfaceMockRecorder) GetAllFlashcards() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllFlashcards", reflect.TypeOf((*MockFlashcardServiceInterface)(nil).GetAllFlashcards))
}

// GetFlashcardByID mocks base method.
func (m *MockFlashcardServiceInterface) GetFlashcardByID(id int) (*models.Flashcard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlashcardByID", id)
	ret0, _ := ret[0].(*models.Flashcard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlashcardByID indicates an expected call of GetFlashcardByID.
func (mr *MockFlashcardServiceInterfaceMockRecorder) GetFlashcardByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlashcardByID", reflect.TypeOf((*MockFlashcardServiceInterface)(nil).GetFlashcardByID), id)
}

// GetRandomFlashcard mocks base method.
func (m *MockFlashcardServiceInterface) GetRandomFlashcard() (*models.Flashcard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandomFlashcard")
	ret0, _ := ret[0].(*models.Flashcard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRandomFlashcard indicates an expected call of GetRandomFlashcard.
func (mr *MockFlashcardServiceInterfaceMockRecorder) GetRandomFlashcard() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomFlashcard", reflect.TypeOf((*MockFlashcardServiceInterface)(nil).GetRandomFlashcard))
}

// UpdateFlashcard mocks base method.
func (m *MockFlashcardServiceInterface) UpdateFlashcard(id int, req *models.UpdateFlashcardRequest) (*models.Flashcard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFlashcard", id, req)
	ret0, _ := ret[0].(*models.Flashcard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateFlashcard indicates an expected call of UpdateFlashcard.
func (mr *MockFlashcardServiceInterfaceMockRecorder) UpdateFlashcard(id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFlashcard", reflect.TypeOf((*MockFlashcardServiceInterface)(nil).UpdateFlashcard), id, req)
}
